package org.payment.processor.domain;

public enum MsgState {
    NONE,
    RECEIVED,
    VALIDATION,
    VALIDATION_FAILED,
    VALIDATION_SUCCESS,
    EXCEPTION,
    REQUEST_CREATION_INITIATED,
    REQUEST_CREATION_COMPLETED,
    PROCESSING_INITIATED,
    PROCESSING_SUCCESS,
    PROCESSING_FAILED,
    PROCESSING_PARTIALLY_FAILED,
    PROCESSING_COMPLETED,
    AGGREGATED,
    RESPONSE_SENT;
}
